description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter_blue: ^0.8.0
  syncfusion_flutter_charts: ^20.4.53
  flutter_reactive_ble: ^5.0.3
  permission_handler: ^10.2.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  circular_countdown_timer: ^0.2.3
  video_player: ^2.6.0
  percent_indicator: ^4.2.3
  quickalert: ^1.0.1


  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.17.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
    - "assets/videos/cprdemo.mp4"
  fonts:
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-700.ttf"
          style: "normal"
          weight: 700
  uses-material-design: true
