import 'package:flutter/material.dart';
import 'package:flutterapp/cprobotappapp/generatedframe1widget/generated/GeneratedCPRobotWidget.dart';
import 'package:flutterapp/cprobotappapp/generatedframe1widget/generated/GeneratedPngfind1Widget.dart';
import 'dart:async';
import 'package:flutterapp/cprobotappapp/generatedframe3widget/videopage.dart';
import 'package:flutterapp/cprobotappapp/generatedframe2widget/GeneratedFrame2Widget.dart';
/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
//Splash screen showing logo and title - animated
class SplashScreen extends StatefulWidget {
  @override
  _SplashScreen createState() => _SplashScreen();
}

class _SplashScreen extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    Timer(Duration(seconds: 3), //load second screen after 3 second delay
            ()=>Navigator.pushReplacement(context,
            MaterialPageRoute(builder:
                (context) =>
                Demo() //go to second widget
            )
        )
    );

  }

  @override
  Widget build(BuildContext context) {
    return Material(
        //child: GestureDetector(
      //onTap: () => Navigator.pushNamed(context, '/GeneratedFrame2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 390.0,
          height: 844.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 95.0,
                  top: 232.0,
                  right: null,
                  bottom: null,
                  width: 225.0,
                  height: 165.0,
                  child: GeneratedCPRobotWidget(),
                ),
                Positioned(
                  left: 106.0,
                  top: 371.0,
                  right: null,
                  bottom: null,
                  width: 199.0,
                  height: 184.0,
                  child: GeneratedPngfind1Widget(),
                ),

                ]),
        ),
      ),
    );
  }
}
