import 'package:flutter/material.dart';
import 'package:flutterapp/cprobotappapp/generatedframe2widget/generated/GeneratedSelectCPRModeWidget.dart';
import 'package:flutterapp/cprobotappapp/generatedframe2widget/generated/GeneratedTrainingWidget.dart';
import 'package:flutterapp/cprobotappapp/generatedframe2widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/cprobotappapp/generatedframe2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cprobotappapp/generatedframe2widget/generated/GeneratedCertificationWidget.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 390.0,
        height: 844.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 99.0,
            top: 240.0,
            right: null,
            bottom: null,
            width: 208.0,
            height: 183.0,
            child: GeneratedRectangle1Widget(),
          ),
          Positioned(
            left: 99.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 208.0,
            height: 183.0,
            child: GeneratedRectangle2Widget(),
          ),
          Positioned(
            left: 76.0,
            top: 98.0,
            right: null,
            bottom: null,
            width: 256.0,
            height: 63.0,
            child: GeneratedSelectCPRModeWidget(),
          ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 117.0,
            height: 70.0,
            child: TransformHelper.translate(
                x: 2.0, y: -100.0, z: 0, child: GeneratedTrainingWidget()),
            ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 152.0,
            height: 66.0,
            child: TransformHelper.translate(
                x: 2.0,
                y: 190.00,
                z: 0,
                child: GeneratedCertificationWidget()),
          )
        ]),
      ),
    ));
  }
}
